apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: filebeat
  namespace: logging-system
  labels:
    app: filebeat
spec:
  selector:
    matchLabels:
      app: filebeat
  template:
    metadata:
      labels:
        app: filebeat
    spec:
      serviceAccountName: filebeat
      terminationGracePeriodSeconds: 30
      volumes:
        - name: varlogcontainers
          hostPath:
            path: /var/log/containers
        - name: config
          configMap:
            name: filebeat-config
        - name: secrets
          secret:
            secretName: elasticsearch-creds
      initContainers:
        - name: filebeat-setup
          image: docker.elastic.co/beats/filebeat:7.12.0
          command: ["/bin/bash", "-c"]
          args:
            - filebeat setup --index-management -E output.elasticsearch.hosts=["http://elasticsearch:9200"]
              -E output.elasticsearch.username="${ELASTICSEARCH_USERNAME}"
              -E output.elasticsearch.password="${ELASTICSEARCH_PASSWORD}"
              -E setup.kibana.host="http://kibana:5601"
          envFrom:
            - secretRef:
                name: elasticsearch-creds
      containers:
        - name: filebeat
          image: docker.elastic.co/beats/filebeat:7.12.0
          securityContext:
              runAsUser: 0
              privileged: true
          args: ["-c", "/etc/filebeat.yml", "-e"]
          env:
            - name: ELASTICSEARCH_URL
              value: "http://elasticsearch:9200"
            - name: ELASTICSEARCH_USERNAME
              valueFrom:
                secretKeyRef:
                  name: elasticsearch-creds
                  key: ELASTIC_USERNAME
            - name: ELASTICSEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: elasticsearch-creds
                  key: ELASTIC_PASSWORD
            - name: KIBANA_URL
              value: "http://kibana:5601"
          volumeMounts:
              - name: config
                mountPath: /etc/filebeat.yml
                readOnly: true
                subPath: filebeat.yml
              - name: secrets
                mountPath: /etc/secrets
              - name: varlibdockercontainers
                mountPath: /var/lib/docker/containers
                readOnly: true
              - name: varlog
                mountPath: /var/log
                readOnly: true
      volumes:
          - name: config
            configMap:
                defaultMode: 0640
                name: filebeat-config
          - name: secrets
            secret:
              secretName: elasticsearch-creds
          - name: varlibdockercontainers
            hostPath:
                path: /var/lib/docker/containers
          - name: varlog
            hostPath:
                path: /var/log