apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: filebeat
  namespace: logging-system
  labels:
    app: filebeat
spec:
  selector:
    matchLabels:
      app: filebeat
  template:
    metadata:
      labels:
        app: filebeat
    spec:
      serviceAccountName: filebeat
      terminationGracePeriodSeconds: 30
      containers:
        - name: filebeat
          image: docker.elastic.co/beats/filebeat:7.12.0
          securityContext:
              runAsUser: 0
              privileged: true
          args: ["-c", "/etc/filebeat.yml", "-e"]
          env:
            - name: ELASTICSEARCH_USERNAME
              valueFrom:
                secretKeyRef:
                  name: elasticsearch-creds
                  key: ELASTIC_USERNAME
            - name: ELASTICSEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: elasticsearch-creds
                  key: ELASTIC_PASSWORD
            - name: KIBANA_USERNAME
              valueFrom:
                secretKeyRef:
                  name: elasticsearch-creds
                  key: KIBANA_USERNAME
            - name: KIBANA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: elasticsearch-creds
                  key: KIBANA_PASSWORD

          volumeMounts:
              - name: config
                mountPath: /etc/filebeat.yml
                readOnly: true
                subPath: filebeat.yml
              - name: secrets
                mountPath: /etc/secrets
              - name: varlibdockercontainers
                mountPath: /var/lib/docker/containers
                readOnly: true
              - name: varlog
                mountPath: /var/log
                readOnly: true
      volumes:
          - name: config
            configMap:
                defaultMode: 0640
                name: filebeat-config
          - name: secrets
            secret:
              secretName: elasticsearch-creds
          - name: varlibdockercontainers
            hostPath:
                path: /var/lib/docker/containers
          - name: varlog
            hostPath:
                path: /var/log
