apiVersion: v1
kind: ServiceAccount
metadata:
  name: filebeat
  namespace: logging-system
  labels:
    k8s-app: filebeat
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: elasticsearch-role
  namespace: logging-system
  labels:
    app: elasticsearch
rules:
- apiGroups: [""]
  resources:
  - namespaces
  - pods
  - services
  - endpoints
  - nodes
  verbs:
  - get
  - watch
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: filebeat-elasticsearch-rb
  namespace: logging-system
subjects:
- kind: ServiceAccount
  name: filebeat
  namespace: logging-system
roleRef:
  kind: Role
  name: elasticsearch-role
  apiGroup: rbac.authorization.k8s.io
