apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: logging-system
data:
  filebeat.yml: |
    filebeat.inputs:
      - type: filestream
        id: kubernetes-container-logs
        paths:
          - /var/log/containers/*.log
        parsers:
          - container: ~
        prospector:
          scanner:
            fingerprint.enabled: true
            symlinks: true
        file_identity.fingerprint: ~
        processors:
          - add_kubernetes_metadata:
              host: minikube
              matchers:
              - logs_path:
                  logs_path: "/var/log/containers/"
          - fingerprint:
              fields: ["source.ip"]
              target_field: "source.fingerprint"
              ignore_missing: false

    output.elasticsearch:
      hosts: ["http://elasticsearch:9200"]
      username: "${ELASTICSEARCH_USERNAME}"
      password: "${ELASTICSEARCH_PASSWORD}"

    setup.kibana:
      host: "http://kibana:5601"
      username: "${KIBANA_USERNAME}"
      password: "${KIBANA_PASSWORD}"

    setup.ilm.enabled: false
    setup.dashboards.enabled: true
    setup.template.enabled: true
    setup.template.name: "filebeat"
    setup.template.pattern: "filebeat-*"
    setup.template.settings:
      index.number_of_shards: 1
      index.number_of_replicas: 0

    logging.level: debug
