apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: logging-system
spec:
  selector:
    matchLabels:
      component: kibana
  template:
    metadata:
      labels:
        component: kibana
    spec:
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:7.12.0
        env:
          - name: ELASTICSEARCH_HOST
            value: "elasticsearch"
          - name: ELASTICSEARCH_PORT
            value: "9200"
          - name: ELASTICSEARCH_USERNAME
            valueFrom:
              secretKeyRef:
                name: elasticsearch-creds
                key: ELASTIC_PASSWORD
          - name: ELASTICSEARCH_USERNAME
            valueFrom:
              secretKeyRef:
                name: elasticsearch-creds
                key: ELASTIC_PASSWORD
        ports:
        - containerPort: 5601
          name: http
          protocol: TCP