apiVersion: v1
kind: Namespace
metadata:
  name: logging-system
---
apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch-creds
  namespace: logging-system
type: Opaque
data:
  ELASTIC_USERNAME: ZWxhc3RpYw==          # base64: elastic
  ELASTIC_PASSWORD: MTIzNDU2Nzg5          # base64: 123456789
  KIBANA_USERNAME: a2liYW5hLXN5c3RlbQ==   # base64: kibana-system
  KIBANA_PASSWORD: MTIzNDU2Nzg5           # base64: 123456789