apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: logging-system
  labels:
    app: elasticsearch
spec:
  cluesteIP: None
  selector:
    app: elasticsearch
    component: elasticsearch
  ports:
    - name: db
      protocol: TCP
      port: 9200
      targetPort: 9200
    - name: monitoring
      protocol: TCP
      port: 9300
      targetPort: 9300
